name: gamemodeselector
version: 1.0-SNAPSHOT
main: org.lurix.gamemodeselector.GamemodeSelectorPlugin
api-version: "1.21"
commands:
  selector:
    description: Spawn gamemode selector displays.
    usage: /selector set <material> <size> <minimessage> | /selector add (<server>) | /selector remove | /selector clear
    permission: gamemodeselector.set
  gamemode:
    description: Alias for selector command.
    usage: /gamemode set <material> <size> <minimessage> | /gamemode add (<server>) | /gamemode remove | /gamemode clear
    permission: gamemodeselector.set
permissions:
  gamemodeselector.set:
    description: Allows creating gamemode selectors.
    default: op
