name: gamemodeselector
version: 1.0-SNAPSHOT
main: org.lurix.gamemodeselector.GamemodeSelectorPlugin
api-version: "1.21"
commands:
  selector:
    description: Spawn gamemode selector displays.
    usage: /selector set <material> <size> <server> <minimessage> | /selector remvove
    permission: gamemodeselector.set
permissions:
  gamemodeselector.set:
    description: Allows creating gamemode selectors.
    default: op
